# tasks file
---
- name: checkout | create directory
  ansible.builtin.file:
    path: "{{ cacti_server_checkout_path }}"
    state: directory
    owner: "{{ cacti_server_default_owner }}"
    group: "{{ cacti_server_default_group }}"
    mode: "{{ cacti_server_default_directory_mode }}"
  tags:
    - cacti-server-pre-checkout-directory

- name: checkout | repository
  ansible.builtin.git:
    repo: "{{ cacti_server_checkout_repo }}"
    dest: "{{ cacti_server_checkout_path }}"
    version: "{{ cacti_server_git_version }}"
    force: true
  register: _git_checkout
  tags:
    - cacti-server-pre-checkout-repository
