# tasks file
---
- name: install | dependencies
  apt:
    name: "{{ cacti_server_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - cacti-server-install-dependencies

- name: install | additional
  apt:
    name: "{{ cacti_server_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - cacti-server-install-additional
