# tasks file for cacti-server
---
- block:

    - include: check.yml
      tags:
        - cacti-server-pre-check

    - include: install.yml
      tags:
        - cacti-server-pre-install

    - include: checkout.yml
      tags:
        - cacti-server-pre-checkout

    - include: configure.yml
      tags:
        - cacti-server-pre-configure

  when: cacti_server_state == 'pre'
  tags:
    - configuration
    - cacti-server
    - cacti-server-pre

- block:

    - include: harden.yml
      tags:
        - cacti-server-post-harden
    - include: poller.yml
      tags:
        - cacti-server-post-poller

  when: cacti_server_state == 'post'
  tags:
    - configuration
    - cacti-server
    - cacti-server-post
