# tasks file
---
- block:

    - include: check.yml
      tags:
        - cacti-server-pre-check

    - include: install.yml
      tags:
        - cacti-server-pre-install

    - include: checkout.yml
      tags:
        - cacti-server-pre-checkout

    - include: configure.yml
      tags:
        - cacti-server-pre-configure

  tags:
    - configuration
    - cacti-server
    - cacti-server-pre

- name: wait for installation to be finished
  command: >
    mysql -Bse "SELECT `cacti` FROM `{{ cacti_server_config_database_default }}`.`version` WHERE `cacti` = '{{ cacti_server_version }}' LIMIT 1;"
  register: _installation_finished
  until: (_installation_finished.stdout_lines | default([]) | length) > 0
  retries: 300
  delay: 1
  changed_when: false
  tags:
    - configuration
    - cacti-server
    - cacti-server-wait

- block:

    - include: harden.yml
      tags:
        - cacti-server-post-harden
    - include: poller.yml
      tags:
        - cacti-server-post-poller

  tags:
    - configuration
    - cacti-server
    - cacti-server-post
