# tasks file for cacti-server
---
# TODO: Check for first install

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ cacti_server_dependencies }}"
  tags:
    - configuration
    - cacti-server
    - cacti-server-dependencies

- name: create (checkout) directory
  file:
    path: "{{ cacti_server_checkout_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - cacti-server
    - cacti-server-checkout

- name: checkout repository
  git:
    repo: "{{ cacti_server_checkout_repo }}"
    dest: "{{ cacti_server_checkout_path }}"
    version: "release/{{ cacti_server_version }}"
    force: true
  register: _git_checkout
  tags:
    - configuration
    - cacti-server
    - cacti-server-checkout

####

- name: create (writable) directories
  file:
    path: "{{ cacti_server_checkout_path }}/{{ item }}/"
    state: directory
    owner: "{{ cacti_server_user }}"
    group: "{{ cacti_server_group }}"
    mode: 0755
  with_items:
    - cache
    - rra
    - log
  tags:
    - configuration
    - cacti-server
    - cacti-server-checkout

- name: update conf file
  template:
    src: "{{ cacti_server_config_file.lstrip('/') }}.j2"
    dest: "{{ cacti_server_config_file }}"
    owner: root
    group: root
    mode: 0640
    validate: 'php -l %s'
  tags:
    - configuration
    - cacti-server
    - cacti-server-update-conf-file

# TODO: Revert after install

- name: make directories writable (for install)
  file:
    path: "{{ cacti_server_checkout_path }}/{{ item }}/"
    state: directory
    owner: "{{ cacti_server_user }}"
    group: "{{ cacti_server_group }}"
    recurse: true
  with_items:
    - resource/snmp_queries
    - resource/script_server
    - resource/script_queries
    - scripts
  tags:
    - configuration
    - cacti-server
    - cacti-server-checkout
