# tasks file for cacti-server
---
- name: poller | schedule
  cron:
    name: poller.php
    job: "php {{ cacti_server_checkout_path }}/poller.php > /dev/null 2>&1"
    minute: "*/5"
    state: "{{ cacti_server_use_poller_php | ternary('present', 'absent') }}"
    cron_file: cacti
    user: "{{ cacti_server_user }}"
  tags:
    - cacti-server-post-poller-schedule
