---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: include vars
      include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
  roles:
    - ../../../
  handlers:
    - import_tasks: "{{ playbook_dir }}/../../tests/handlers/main.yml"
